# Generated by Django 4.1.7 on 2023-05-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Username',
            new_name='username',
        ),
    ]
